services:
  - type: web
    name: whatsapp-baileys-server
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
    disk:
      name: whatsapp-auth-data
      mountPath: /data
      sizeGB: 1
